Repository YAPP-Github/onboard-aos, pull requests merged in 2023-09, with the labels that each got.

#136 [BOL-376-1] Home 관련 QA 이슈 해결
  presentation/src/main/java/com/yapp/bol/presentation/view/home/rank/HomeRankFragment.kt
  presentation/src/main/java/com/yapp/bol/presentation/view/home/rank/HomeUiState.kt
  presentation/src/main/java/com/yapp/bol/presentation/view/home/rank/HomeUiStateNeedRefactor.kt
  presentation/src/main/java/com/yapp/bol/presentation/view/home/rank/UserRankViewModel.kt
  presentation/src/main/res/layout/view_rank_2nd.xml
  presentation/src/main/res/layout/view_rank_3rd.xml
Labels: bug

#141 [BOL-376-base]
  presentation/src/main/java/com/yapp/bol/presentation/view/home/HomeActivity.kt
  presentation/src/main/java/com/yapp/bol/presentation/view/home/HomeViewModel.kt
  presentation/src/main/java/com/yapp/bol/presentation/view/home/rank/HomeRankFragment.kt
  presentation/src/main/java/com/yapp/bol/presentation/view/home/rank/HomeUiState.kt
  presentation/src/main/java/com/yapp/bol/presentation/view/home/rank/HomeUiStateNeedRefactor.kt
  presentation/src/main/java/com/yapp/bol/presentation/view/home/rank/UserRankViewModel.kt
  presentation/src/main/java/com/yapp/bol/presentation/view/match/game_result/GameResultFragment.kt
  presentation/src/main/res/layout/view_group_search.xml
  presentation/src/main/res/layout/view_rank_2nd.xml
  presentation/src/main/res/layout/view_rank_3rd.xml
Labels: base

#144 [BOL385] 임시 멤버 추가 중복된 네임 없을 경우 문구 버그 수정 (Debounce 기능)
  presentation/src/main/java/com/yapp/bol/presentation/view/match/dialog/GuestAddDialog.kt
  presentation/src/main/java/com/yapp/bol/presentation/view/match/member_select/MemberSelectFragment.kt
Labels: bug

#152 [BOL-362] 홈에 '나'를 나타내는 UI 추가
  data/src/main/java/com/yapp/bol/data/mapper/GroupMapper.kt
  data/src/main/java/com/yapp/bol/data/model/group/UserRankDTO.kt
  domain/src/main/java/com/yapp/bol/domain/model/UserRankItem.kt
  presentation/src/main/java/com/yapp/bol/presentation/mapper/HomeMapper.kt
  presentation/src/main/java/com/yapp/bol/presentation/model/UserRankUiModel.kt
  presentation/src/main/java/com/yapp/bol/presentation/view/home/rank/UserRankViewModel.kt
  presentation/src/main/java/com/yapp/bol/presentation/view/home/rank/user/UserRankAdapter.kt
  presentation/src/main/java/com/yapp/bol/presentation/view/home/rank/user/UserRankItem1to3ViewHolder.kt
  presentation/src/main/java/com/yapp/bol/presentation/view/home/rank/user/UserRankItemAfter4ViewHolder.kt
  presentation/src/main/res/layout/item_rank_after_4.xml
  presentation/src/main/res/layout/view_rank_1st.xml
  presentation/src/main/res/layout/view_rank_2nd.xml
  presentation/src/main/res/layout/view_rank_3rd.xml
  presentation/src/main/res/layout/view_rank_me.xml
Labels: enhancement
